#!/bin/bash

echo "=== 轻量级构建脚本 ==="
echo "这个脚本会跳过一些可能导致内存问题的步骤"

# 设置Node.js内存限制
export NODE_OPTIONS="--max-old-space-size=4096"

# 清理输出目录
echo "清理输出目录..."
rm -rf dist/webapp/*

# 只运行必要的步骤
echo "运行必要的构建步骤..."

# 1. 合并国际化文件
echo "1. 合并国际化文件..."
node -e "
const fs = require('fs');
const path = require('path');
const i18nDir = 'src/webapp/i18n';
const modulesRoot = 'src/webapp/app/modules/';
var allLangs = {};
fs.readdirSync(i18nDir).map(file => {
    var filePath = path.join(i18nDir, file);
    if (fs.statSync(filePath).isDirectory()) {
        var langKey = path.basename(file);
        allLangs[langKey] = {};
        fs.readdirSync(filePath).filter(file => {
            var str = fs.readFileSync(path.join(filePath, file));
            Object.assign(allLangs[langKey], JSON.parse(str));
        });
    }
});
var content = '// This file is generated by gulp.\n// DO NOT EDIT THIS FILE !\n// Edit i18n JSON file instead.\n\n;(function() {\n  window[\"@oplus/langs\"]=' + JSON.stringify(allLangs, null, 2) + ';\n})();';
fs.writeFileSync(path.join(modulesRoot, 'oplus-lang.js'), content);
console.log('国际化文件合并完成');
"

# 2. 复制必要文件
echo "2. 复制必要文件..."
mkdir -p dist/webapp
cp -r src/webapp/content dist/webapp/
cp -r src/webapp/app dist/webapp/
cp src/webapp/config.js dist/webapp/
cp src/webapp/index.html dist/webapp/

# 3. 复制vendor库
echo "3. 复制vendor库..."
mkdir -p dist/webapp/lib
cp -r src/webapp/lib/* dist/webapp/lib/ 2>/dev/null || true

# 4. 复制node_modules中的必要文件
echo "4. 复制node_modules中的必要文件..."
mkdir -p dist/webapp/node_modules
cp -r node_modules/angular dist/webapp/node_modules/ 2>/dev/null || true
cp -r node_modules/lodash dist/webapp/node_modules/ 2>/dev/null || true
cp -r node_modules/jquery dist/webapp/node_modules/ 2>/dev/null || true
cp -r node_modules/bootstrap dist/webapp/node_modules/ 2>/dev/null || true

echo "=== 轻量级构建完成 ==="
echo "输出目录: dist/webapp/"
echo "注意: 这是一个简化版本，可能缺少一些优化功能" 